### ISSUE TITLE
Installation of Ussd Airflow

### ISSUE THREAD

**Issue by eliaskioni** [mwaaas/ussd_airflow#30]
-  Installing ussd_airflow from pypi is a challenge.

- Getting this error 

- Traceback (most recent call last):                                                                                                                                      
  File "manage.py", line 22, in <module>                                                                                                                                
    execute_from_command_line(sys.argv)                                                                                                                                 
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line                                              
    utility.execute()                                                                                                                                                   
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 341, in execute                                                                
    django.setup()                                                                                                                                                      
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 27, in setup                                                                                   
    apps.populate(settings.INSTALLED_APPS)                                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 115, in populate                                                                          
    app_config.ready()                                                                                                                                                  
  File "/usr/local/lib/python3.5/dist-packages/ussd/apps.py", line 19, in ready                                                                                         
    from ussd import screens                                                                                                                                            
ImportError: cannot import name 'screens'

**Comment by mwaaas** [comment]
fixed by #33
